INSERT INTO employee (first_name, last_name, role, manager_id)
VALUES ("John", "Smith", 10, NULL),
       ("Marcus", "Wright", 4, 1),
       ("Cody", "Begg", 1, 1),
       ("Mary", "Lewis", 2, 3),
       ("Cynthia", "Paltry", 3, 4),
       ("Dru", "Douglas", 5, 2),
       ("Sarah", "Patton", 6, 1),
       ("Kristin", "Cartwright", 6, 1),
       ("Kyle", "Weber", 7, 7),
       ("John", "Doe", 7, 8),
       ("Natalie", "Portman", 8, 2),
       ("Kevin", "Bacon", 9, 11),
       ("James", "Bobbin", 9, 11),
       ("Denise", "Fig", 9, 11),
       ("Sherry", "Deckert", 11, 1),
       ("Marcus", "Deacon", 12, 15),
       ("Joseph", "Josephs", 13, 12),
       ("Laurelai", "Gilmore", 13, 12),
       ("Rory", "Gilmore", 13, 12);